packet: Fixed a NameError in an exception
I introduced a NameError at some stage:
  File "/home/muelli/vcs/python-pgpdump/pgpdump/__main__.py", line 13, in parsefile
    for packet in data.packets():
  File "/home/muelli/vcs/python-pgpdump/pgpdump/data.py", line 34, in packets
    total_length, packet = construct_packet(self.data, offset)
  File "/home/muelli/vcs/python-pgpdump/pgpdump/packet.py", line 590, in construct_packet
    packet = PacketType(tag, name, new, packet_data)
  File "/home/muelli/vcs/python-pgpdump/pgpdump/packet.py", line 148, in __init__
    super(SignaturePacket, self).__init__(*args, **kwargs)
  File "/home/muelli/vcs/python-pgpdump/pgpdump/packet.py", line 22, in __init__
    self.parse()
  File "/home/muelli/vcs/python-pgpdump/pgpdump/packet.py", line 166, in parse
    "%02x" % (offset, data[offset]))
NameError: global name 'data' is not defined

It should have been self.data of course.